name: Jamanvav
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #FIREBASE....
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.5.6

  #GETX.....
  sizer: ^2.0.15
  flutter_image_compress: ^2.0.3
  path_provider: ^2.0.15
  get: ^4.6.5
  get_storage: ^2.1.1
  connectivity_plus: ^3.0.4
  shared_preferences: ^2.2.1
  flutter_email_sender: ^6.0.2
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.5
#  octo_image: ^1.0.2
  cached_network_image: ^3.2.3
#  shimmer_animation: ^2.1.0+1
  pinput: ^3.0.1
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  lottie: ^2.7.0
  photo_view: ^0.14.0
  open_store: ^0.5.0
  package_info_plus: ^5.0.1
  flutter_slidable: ^3.0.1
  url_launcher: ^6.2.3
  flutter_local_notifications:
  firebase_messaging:
  http:
  text_scroll: ^0.2.0
  intl: ^0.19.0


  dropdown_search:
    path: packages/searchable_dropdown-master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/FontsFree-Net-DMSerifDisplay-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

