// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFCuGp1jMix597-URqzqc264sQwg7ix8',
    appId: '1:922434770130:web:9ccb2d45c7fc1d07e7090b',
    messagingSenderId: '922434770130',
    projectId: 'katedu-4ddd8',
    authDomain: 'katedu-4ddd8.firebaseapp.com',
    storageBucket: 'katedu-4ddd8.appspot.com',
    measurementId: 'G-EYBTENRYRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVr0kHx8M8DC4NjH7XtqUPjrIsrMmck_s',
    appId: '1:489376848429:android:56d46000a17288cb7b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlFCuGp1jMix597-URqzqc264sQwg7ix8',
    appId: '1:922434770130:ios:788777f78e07a1abe7090b',
    messagingSenderId: '922434770130',
    projectId: 'katedu-4ddd8',
    storageBucket: 'skatedu-4ddd8.appspot.com',
    iosBundleId: 'com.katedu.madvise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlFCuGp1jMix597-URqzqc264sQwg7ix8',
    appId: '1:305377445641:ios:0fb74779efcabae1a4f5d8',
    messagingSenderId: '305377445641',
    projectId: 'snehmilan-816cc',
    storageBucket: 'snehmilan-816cc.appspot.com',
    iosBundleId: 'com.madvise.jamanedu.RunnerTests',
  );
}
